sudo: required 
language: cpp
services:
  - docker
env:
  global:
    secure: "bDWWc4Uylf+n6Kh5i0AADyrdEd1iFAbt1lLJkBoKP1mWrXUSUKETKxaQsDH66qvmqZ6GQKcOdHwgpA0gV9thCNob5TIh0Un5FEork5HGAffGenCCHU3uh9u7ksy/Zd5ySTtdO0d2QT/Kreh5RLxqwhcD7MCXP4JU/D/Mdetsm/Jbhwwfv/ZPSaWHUFkS++VFtZ2FxizX50LOFGC2gXbShszND6Ri6pLN4mEGY3UKDZvpIn8iBS1C1kV1/2I+X2lnxJGU9p3mrvdEZqa/nE7LKB0cJEzs/xfXXz4TRvi4kE/koQ2nw+7wVd39C2Ap330neUP04/IUlYFssYTY+LSI/gOZ+zvwjhBfD/kvatH3HyUISZI3vFNMGNmCyxRFcZebrx3D4cwJ2pIFt6iyQJ+UNBlDf+M9xQujyda0dpPDtBLf4+n7EQuV738ZyCUIEUFzFW9rSg8Alwc35N73mnAdSkKRJAqbQI2+7ScH+wKy6WrkQgQia0wXlHW2oTdMu9wEobaeg9tyRPcxS/zI/NSV24IzFsjHvJpgcMmSGJoM0mSNJGvtFU2dtEXlqwlAca+eQQ4pIYTay1ZGPnhHYQGIdesUVB4b1YjXWzy43q2V3LQgZhePHeye73u0sTT5hP9dodiySfZN1bN+U0EFONVqvecdxbreN8Q8Ldnn7HIjYh4=" #BINTRAY_KEY

before_install:
  - mkdir $(pwd)/build
  - docker pull spielhuus/toolchain:latest
script:
  - sudo docker run -itd -v $(pwd)/repo:/repo --name conan_build spielhuus/toolchain /bin/bash 
  - sudo docker exec conan_build /bin/bash -c "git clone https://github.com/spielhuus/conan-hiredis.git /repo"
  - sudo docker exec conan_build /bin/bash -c "conan user -p $BINTRAY_KEY -r conan-cpp squawkcpp"
  - sudo docker exec conan_build /bin/bash -c "cd /repo && conan export . conan-cpp/latest && conan install hiredis/0.13.3@conan-cpp/latest --build=hiredis && conan upload hiredis/0.13.3@conan-cpp/latest --all -r=conan-cpp"
  - sudo docker rm -f conan_build

